### ISSUE TITLE
Cannot use this socket. Please specify another socket

### ISSUE THREAD

**Issue by chamalis** [melissiproject/client#10]
When trying to start melissi client I get:

Cannot use this socket. Please specify another socket

my ~/.config/melissi/config 
file contains:

``` code
username = chefarov
no-desktop = False
resource = redalert
socket = /home/chefarov/.config/melissi/melissi.sock
database = sqlite:////home/chefarov/.config/melissi/melissi.db
new-root-path = /home/chefarov
host = http://localhost:8000/
desktop-notifications = True
password = chefarov
```

I had to delete the ~/.config/melissi/melissi.sock which fixed the problem

**Comment by glogiotatidis** [comment]
solved on dev branch. We switch from using unix socket to using dbus. thnx for reporting
